name=EcoWifi
version=1.0.0
author=Huu-Phuoc Nguyen <huuphuoc.research@gmail.com>
maintainer=Huu-Phuoc Nguyen <huuphuoc.research@gmail.com>
sentence=A library to manage WiFi connection and SmartConfig-like web portal setup for ESP8266 and ESP32.
paragraph=This library allows ESP8266 and ESP32 to easily connect to WiFi and provides a captive portal for setting up a new WiFi connection seamlessly.
category=Communication
url=https://github.com/HuuPhuoc2411/EcoWifi
architectures=esp8266,esp32
